require:
  - ./rubocop/eiseron/no_comments.rb

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - rubocop/**/*

Eiseron/NoComments:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/eiseron_automation/preview/deploy.rb
    - lib/eiseron_automation/preview/teardown.rb

Metrics/AbcSize:
  Max: 20
  Exclude:
    - lib/eiseron_automation/preview/deploy.rb
    - test/**/*

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*
    - lib/eiseron_automation/cli.rb
    - lib/eiseron_automation/gitlab_client.rb
    - lib/eiseron_automation/preview/deploy.rb

Metrics/ParameterLists:
  Exclude:
    - test/**/*
    - lib/eiseron_automation/preview/deploy.rb
    - lib/eiseron_automation/preview/stop.rb
    - lib/eiseron_automation/preview/sweep.rb
    - lib/eiseron_automation/preview/diagnostics.rb
    - lib/eiseron_automation/db/schedule.rb

Layout/LineLength:
  Exclude:
    - lib/eiseron_automation/preview/deploy.rb
    - lib/eiseron_automation/preview/teardown.rb
    - lib/eiseron_automation/preview/diagnostics.rb
